name: infra
on:
  push:
    branches:
      - main
  workflow_dispatch: {}
jobs:
  infra:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      latest_commit: ${{ steps.git_remote.outputs.latest_commit }}
    env:
      CI: "true"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.1.2
      - name: Install dependencies
        run: yarn install --check-files --frozen-lockfile
      - name: Deploy infrastructure
        run: yarn deploy
        env:
          TERRAFORM_CLOUD_TOKEN: ${{ secrets.TERRAFORM_CLOUD_TOKEN }}
